### ISSUE TITLE
instalación del entorno de desarrollo

### ISSUE THREAD

**Issue by LuisCaPacheco** [ISCOUTB/AH-ToolCheck#10]

**Comment by Tkyzxim** [comment]
try this
https://gofile.io/d/yMHabA
select the desired compiler in the installer

**Comment by LK4SNIPER** [comment]
Para nuestro software, usaremos Visual Studio como entorno de desarrollo. 

Visual Studio es un Entorno de Desarrollo Integrado (IDE) robusto, ideal para desarrollar aplicaciones, incluyendo la creación de APIs, gestión de bases de datos e integración con Docker. Ofrece un conjunto completo de herramientas que simplifican el ciclo de vida del desarrollo de software.

**Beneficios al usar Visual Studio:**
  

1. Creación de APIs:
  
    1.   Proporciona plantillas predefinidas para construir APIs en tecnologías como ASP.NET Core, facilitando la creación rápida y eficiente de APIs RESTful.
    2.   Ofrece integración con Swagger para documentar y probar APIs directamente desde el entorno de desarrollo.

2. Base de Datos:
    
    1. Permite gestionar bases de datos usando SQL Server Data Tools (SSDT).
    2. Se pueden diseñar, depurar y administrar bases de datos sin salir del IDE.
    3. Soporta conexiones a diversas bases de datos (SQL Server, MySQL, PostgreSQL, etc.), lo que facilita la administración de los datos directamente desde Visual Studio.

3. Integración con Docker:

    1. Visual Studio permite agregar soporte para contenedores Docker en aplicaciones .NET Core, facilitando la creación y despliegue de aplicaciones dentro de contenedores.
    2. Integra herramientas para crear archivos Dockerfile y gestionar imágenes de Docker, asegurando que el entorno de desarrollo sea reproducible y adecuado para producción.

**Cómo instalar Visual Studio (breve guía):**

1. Descargar Visual Studio desde la página oficial de Microsoft (https://visualstudio.microsoft.com/).

2. Ejecutar el instalador y seleccionar las cargas de trabajo:

    1. Desarrollo de ASP.NET y aplicaciones web para APIs.
    2. Desarrollo de bases de datos para trabajar con bases de datos.
    3. Herramientas de contenedores y Docker para integración con Docker.

3. Completar la instalación y comenzar a desarrollar.

**Comment by jairoserrano** [comment]
adelante
