### ISSUE TITLE
Seguridad y Rendimiento

### ISSUE THREAD

**Issue by LK4SNIPER** [ISCOUTB/AH-ToolCheck#2]
- REQ-004.1: El sistema debe implementar medidas de seguridad robustas para proteger los datos de los usuarios.

- REQ-004.2: El sistema debe ser eficiente y capaz de manejar múltiples consultas simultáneamente.

**Comment by LuisCaPacheco** [comment]
[https://github.com/ISCOUTB/AH-ToolCheck/blob/master/Dockerfile](https://github.com/ISCOUTB/AH-ToolCheck/blob/master/Dockerfile)

**Comment by LuisCaPacheco** [comment]
Arreglamos el Problema de Seguridad
