### ISSUE TITLE
Creacion de Base de datos SQL y NO SQL

### ISSUE THREAD

**Issue by LuisCaPacheco** [ISCOUTB/AH-ToolCheck#6]

**Comment by sbertel31** [comment]
Para la base de datos SQL, se ha seleccionado MySQL con el motor de almacenamiento InnoDB. Este motor es ideal para manejar transacciones y asegurar la integridad referencial a través de claves primarias y foráneas, lo que es esencial para aplicaciones que requieren consistencia y operaciones seguras.

Beneficios de MySQL:
Consistencia y seguridad de los datos: Gracias a las propiedades ACID, las transacciones son fiables y consistentes.
Amplia compatibilidad: MySQL es ampliamente compatible con una variedad de aplicaciones web y frameworks de desarrollo.
Motor InnoDB: Este motor de almacenamiento soporta transacciones, lo que asegura la consistencia de los datos en operaciones críticas.
Integración con aplicaciones web:
Se utilizará Docker Compose para facilitar la configuración y despliegue de la base de datos MySQL junto a una aplicación web.

Además de MySQL, se integrará una base de datos NoSQL, que nos ayudará a gestionar grandes volúmenes de datos no estructurados o semi-estructurados y proporcionar mayor flexibilidad en el manejo de la información. Al incorporar una base de datos NoSQL, el sistema podrá escalar de manera eficiente, manejar datos que cambian con frecuencia y ofrecer tiempos de respuesta rápidos para consultas específicas.

**Comment by jairoserrano** [comment]
adelante
