### ISSUE TITLE
Elegir Motor para el SQL

### ISSUE THREAD

**Issue by LuisCaPacheco** [ISCOUTB/AH-ToolCheck#7]

**Comment by LuisCaPacheco** [comment]
Utilizaremos un motor para MySQL que es INNODB


[Motor SQL.docx](https://github.com/user-attachments/files/16923887/Motor.SQL.docx)

**Comment by jairoserrano** [comment]
Seleccionado entonces. procedan a buscar qué imágenes y versiones de docker les funcionará.
