### ISSUE TITLE
creación de la Infraestructura (Docker)

### ISSUE THREAD

**Issue by LuisCaPacheco** [ISCOUTB/AH-ToolCheck#8]

**Comment by LK4SNIPER** [comment]
**Integración de Docker con MySQL e INNODB**

Se puede integrar la base de datos MySQL con aplicaciones web o servicios usando Docker Compose. Aquí **ejemplo básico** de un archivo docker-compose.yml que integra una aplicación web y un contenedor MySQL con InnoDB:

    version: '3.1'
    
    services:
      db:
        image: mysql:latest
        environment:
          MYSQL_ROOT_PASSWORD: my-secret-pw
          MYSQL_DATABASE: mydb
          MYSQL_USER: user
          MYSQL_PASSWORD: userpassword
        volumes:
          - ./mysql_data:/var/lib/mysql
        ports:
          - "3306:3306"
    
      web:
        image: my-web-app
        depends_on:
          - db
        ports:
          - "8080:80"

**Comment by jairoserrano** [comment]
esa es la idea, pero debemos salir del ejemplo
